[package]
name = "chatteroo"
version = "0.1.0"
edition = "2021"

[dependencies]
ax25 = "0.3"
ax25_tnc = "0.3"
crc32fast = "1.3"
rusqlite = { version = "0.30.0", features = ["bundled", "time"] }
time = { version = "0.3", features = ["macros"] }
thiserror = "1.0"
